apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: greetings-ticker
build:
  artifacts:
  - image: quay.io/rhdevelopers/greetings-ticker
  local:
     push: false
deploy:
  kubectl:
    manifests:
    - k8s/app.yaml
