apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: lingua-greeter
build:
  local:
    push: false
  artifacts:
  - image: rhdevelopers/lingua-greeter
    context: .
    docker:
      dockerfile: src/main/docker/Dockerfile.jvm
deploy:
  kustomize: {}
profiles:
  - name: jupiter
    deploy:
      kustomize:
        paths:
        - ./overlays/jupiter
    activation:
      - env: CLOUD_PROFILE=jupiter
  - name: mars
    deploy:
      kustomize:
        paths:
        - ./overlays/mars
    activation:
      - env: CLOUD_PROFILE=mars
  

